### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tilmanbeck** [lschmelzeisen/nasty#9]
Hi,

while running a nasty batch request via command line, one of my search terms failed with the following error message:
```
"exception": {
    "time": "2020-05-01T20:58:12.156301",
    "type": "IndexError",
    "message": "IndexError: list index out of range",
    "trace": [
      [ 
        "  File \"/home/beck/Data/corona-crawl/venv/lib/python3.6/site-packages/nasty/batch/batch.py\", line 115, in _execute_entry",
        "    write_jsonl_lines(data_file, entry.request.request(), use_lzma=True)"
      ],
      [ 
        "  File \"/home/beck/Data/corona-crawl/venv/lib/python3.6/site-packages/nasty/_util/json_.py\", line 137, in write_jsonl_lines",
        "    use_lzma=use_lzma,"
      ],
      [ 
        "  File \"/home/beck/Data/corona-crawl/venv/lib/python3.6/site-packages/nasty/_util/io_.py\", line 85, in write_lines_file",
        "    for value in values:"
      ],
      [ 
        "  File \"/home/beck/Data/corona-crawl/venv/lib/python3.6/site-packages/nasty/_util/json_.py\", line 135, in <genexpr>",
        "    (json.dumps(value.to_json()) for value in values),"
      ],
      [ 
        "  File \"/home/beck/Data/corona-crawl/venv/lib/python3.6/site-packages/nasty/_retriever/retriever.py\", line 66, in __next__",
        "    if not self._update_callback():"
      ],
      [ 
        "  File \"/home/beck/Data/corona-crawl/venv/lib/python3.6/site-packages/nasty/_retriever/retriever.py\", line 214, in _update_tweet_stream",
        "    self._fetch_new_twitter_session()"
      ],
      [ 
        "  File \"/home/beck/Data/corona-crawl/venv/lib/python3.6/site-packages/nasty/_retriever/retriever.py\", line 320, in _fetch_new_twitter_session",
        "    )[0]"
      ]
    ]
```

Here are the request parameters:
```
"request": {
    "type": "Search",
    "query": "coronavirus",
    "since": "2019-12-01",
    "until": "2020-03-16",
    "filter": "LATEST",
    "lang": "en",
    "max_tweets": null
  }
```
Some other search requests from the same batch-processing file finished successfully.

**Comment by lschmelzeisen** [comment]
This is going to be hard for me to replicate, since your request spans such a large timespan.

In general, I suggest using the `--daily` flag to convert long running requests into smaller ones. For example, you would run something like:

```sh
nasty search --query coronavirus --since 2019-12-01 --until 2019-12-03 --to-batch batch.jsonl --daily
```

To create a `batch.jsonl` file with the following `Search` requests:

```json
{"id": "2f459c5312ce45699ac3a57c1b93aa05", "request": {"type": "Search", "query": "coronavirus", "since": "2019-12-01", "until": "2019-12-02", "filter": "TOP", "lang": "en"}}
{"id": "38c4fa2fd6424b30a9b2f717e710568b", "request": {"type": "Search", "query": "coronavirus", "since": "2019-12-02", "until": "2019-12-03", "filter": "TOP", "lang": "en"}}
{"id": "f68f3f82ad2a4935ae0c19b8b6f9a954", "request": {"type": "Search", "query": "coronavirus", "since": "2019-12-03", "until": "2019-12-04", "filter": "TOP", "lang": "en"}}
```

(By the way, if the file already exists the command will simply append to it.)

Then you can run all requests in the batch file via:

```sh
nasty batch --batch-file batch.jsonl --results-dir out/
```

This has the advantage that should an individual request fail for any reason the others can still succeed. And it makes it much easier for me to replicate what is actually going wrong. Also, if something does indeed go wrong, you can just rerun the above command: it will autmatically figure out which did not complete yet and only run those.

(By the way, I suggest appending something like `--log-level DEBUG >> out.log 2>&1` to the `nasty batch` command, so that you will always get a detailed log, which you can forward to me.)

**Comment by broganyoung** [comment]
Hello, I now get this same error for every search that I am making. I've done a fresh install of everything and even the simple searches in the Readme fail. It happens both with the command line and with using the Python API. It still writes batch files without any problem but it fails every search if it reads one. 

As an example, if I run `nasty search --query "climate change"` I get the following:

> Traceback (most recent call last):
>   File "C:\Users\broga\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\broga\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\broga\PycharmProjects\untitled2\venv\Scripts\nasty.exe\__main__.py", line 7, in <module>
>   File "c:\users\broga\pycharmprojects\untitled2\venv\lib\site-packages\nasty\cli\main.py", line 55, in main
>     command.run()
>   File "c:\users\broga\pycharmprojects\untitled2\venv\lib\site-packages\nasty\cli\_request_command.py", line 105, in run
>     for tweet in request.request():
>   File "c:\users\broga\pycharmprojects\untitled2\venv\lib\site-packages\nasty\request\search.py", line 149, in request
>     return SearchRetriever(self).tweet_stream
>   File "c:\users\broga\pycharmprojects\untitled2\venv\lib\site-packages\nasty\_retriever\retriever.py", line 174, in __init__
>     self._fetch_new_twitter_session()
>   File "c:\users\broga\pycharmprojects\untitled2\venv\lib\site-packages\nasty\_retriever\retriever.py", line 318, in _fetch_new_twitter_session
>     guest_token = re.findall(
> IndexError: list index out of range

Not sure if I am doing something really obviously wrong since it had been working fine previously? Any help would be really appreciated!

**Comment by lschmelzeisen** [comment]
Just confirming that I receive the same error on my end. Note that it is somewhat expected that errors like this will appear from time to time since we are not using any official API (so it's not you doing something wrong). I will try to take a look at fixing this next week.

**Comment by broganyoung** [comment]
Don't know if you looked into this, but the issue seems to have resolved itself? Everything is working fine now, and the output is all correct. I checked it a day or so ago on a whim, so haven't changed anything. Must have been something on Twitter's side? Either way, it's working great!

**Comment by lschmelzeisen** [comment]
No, I actually did not find the time to look into this. I did not change anything but can confirm that it works again, indeed.

I'm closing this for now, feel free to re-open if this issue or something similar comes back up.

As a side note, something like this happening from time to time is expected behavior since NASTY is not using any public API. Usually, I will try to fix the problem myself than trying to wait until it magically fixes itself though. Hopefully, the code base will over time converge to something that is a bit more resilient against minor changes on Twitter's side.

**Comment by broganyoung** [comment]
I know you closed this, but just to let you know that the same error cropped up again at about midnight last night (GMT) and has persisted until now. I'll keep an eye on it and see if it gets going again though. Thanks!

**Comment by broganyoung** [comment]
I had a look about the retriever.py file. I'm definetely not an expert, but it seems like it uses the mobile browser? [Twitter pushed an update yesterday to the mobile.twitter.com site](https://twitter.com/i/release_notes). 

Don't know if that helps you! Couldn't see what might have broken the retriving bit, but the update before this was around the time I got that error the first time. Seems like it might be linked though.

**Comment by broganyoung** [comment]
Okay, I found and fixed what the problem was. 

In retriver.py there is this:

`main_js_url = re.findall(
            "(https://abs.twimg.com/responsive-web/web/main.[a-z0-9]+.js)",
            response.text,
        )[0]`

The problem is that `"(https://abs.twimg.com/responsive-web/web/main.[a-z0-9]+.js)"` isn't appearing in the response text. However, `"(https://abs.twimg.com/responsive-web/web_legacy/main.[a-z0-9]+.js)"` does. I assume that when Twitter updates its PW applications (like mobile.twitter.com) the abs.twimg is not updated with it immediately and is re-labelled as legacy. 

Changing the search term to `"(https://abs.twimg.com/responsive-web/web_legacy/main.[a-z0-9]+.js)"` solves the issue I was having. I guess this will stop working once the abs.twimg site is updated back to /web/. I'm sure there is an easy way to have it search for both? 

Thanks! Issue is really closed now!

**Comment by lschmelzeisen** [comment]
Hey everyone, I finally found the time to look into this and hopefully fix it for good. On my machine, all tests are passing for the moment. [I published a new version 0.2.3 to pip](https://pypi.org/project/nasty/0.2.3/). However, it does not seem to be installable via `pip install nasty==0.2.3` yet. I suspect there are some caching delays involved from the PyPI serves and assume this fixes itself. If this does not happen in the next two days, I will try to look at it again.

If you want the update urgently (I realize it has taken me quite some time to respond to this), you should be able to install via git:

```
pip install nasty@git+git://github.com/lschmelzeisen/nasty#egg=nasty
```

@broganyoung: Big thanks for taking the time to investigate the error! This made fixing it a lot easier for me. I now used the regex `https://abs.twimg.com/responsive-web/web(?:_legacy)?/main.[a-z0-9]+.js` since they seem to switch back to just using `web` sometimes? At least, this is what I suspect from it working again for a short time.

If this or a similar error starts popping up again, please re-open or raise a new issue!

**Comment by lschmelzeisen** [comment]
Indeed, the updated version is now available on pip. You can now update via `pip install -U nasty`.

**Comment by g-vallejo** [comment]
I'm still having the same issue. Even after updating NASTY :(.

**Comment by broganyoung** [comment]
Did you try the fix I mentioned?

**Comment by g-vallejo** [comment]
Yeah! I hard-coded the solution. The problem now is that `https://abs.twimg.com/responsive-web/web(?:_legacy)?/main.[a-z0-9]+.js` doesn't work anymore, because response now has this: `https://abs.twimg.com/responsive-web/client-web-legacy/main.[a-z0-9]+.js`.  Both @broganyoung and @lschmelzeisen answers helped to find the issue. But it seems like this will continue happening.

**Comment by JulianNaumann** [comment]
I have the same problem as @gisvl. On v0.2.3. Her new link fixed it for now

**Comment by iurshina** [comment]
Had the same issue (v0.2.4), @gisvl comment helped.

**Comment by lschmelzeisen** [comment]
Seems like this problem had resurfaced. I just pushed out a new version 0.2.5 where this should be fixed.

Thanks to everyone for reporting this and especially @gisvl for looking up the new URL. Theoretically, this should mean that I could have fixed this very fast. However, I was quite busy in other areas of my life. I'll try to be much quicker in the future!
